namespace WFTools.Services.Tracking.Ado
{
    /// <summary>
    /// All parameter names used for executing commands against 
    /// the tracking store.
    /// </summary>
    public enum TrackingParameterName
    {
        ActivityInstanceId, 
        ActivityStatusId, 
        ActivityStatusEventId,
        ActivityXml, 
        ActivityXoml, 
        Annotation,
        AssemblyFullName,
        CallerContextGuid,
        CallerInstanceId, 
        CallerParentContextGuid,
        CallPath,
        ContextGuid, 
        CreateDefault,
        DataBlob, 
        DataNonSerialisable,
        DataString, 
        EndDate, 
        EventArgs, 
        EventArgsAssemblyFullName, 
        EventArgsTypeFullName,
        EventDateTime, 
        EventId, 
        EventOrder, 
        EventType, 
        Exists,
        FieldName, 
        InitialisedDateTime, 
        InstanceId,
        IsInstanceType,
        LastCheck, 
        MaxResults, 
        NextCheck, 
        Order, 
        ParentContextGuid, 
        ParentQualifiedName, 
        QualifiedName,
        StartDate, 
        StartOffset, 
        TrackingDataItemId, 
        TrackingProfile, 
        TrackingWorkflowInstances,
        TypeFullName, 
        Version,
        UserDataAssemblyFullName, 
        UserDataBlob,
        UserDataKey, 
        UserDataNonSerialisable, 
        UserDataString, 
        UserDataTypeFullName, 
        UserEventId, 
        WorkflowDefinition, 
        WorkflowTypeId,
        WorkflowInstanceEventId,
        WorkflowInstanceId,
        WorkflowInstanceStatusId, 
    }
}