//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.Workflow.Services.Controls.Navigation
{
    using System;
    using System.ComponentModel;
    using System.Workflow.Activities;
    using System.Workflow.ComponentModel;
    using System.Workflow.ComponentModel.Design;
    using System.Workflow.ComponentModel.Compiler;
    using HA.Workflow.Services.Interfaces;


    [ToolboxItemAttribute(typeof(ActivityToolboxItem))]
    public partial class GoNext : HandleExternalEventActivity
    {

        public static DependencyProperty EProperty = DependencyProperty.Register("E", typeof(StateBehaveArgs), typeof(GoNext));

        public GoNext()
        {
            base.InterfaceType = typeof(IStateBehaveCondition);
            base.EventName = "GoNext";
        }

        [BrowsableAttribute(false)]
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Hidden)]
        public override System.Type InterfaceType
        {
            get
            {
                return base.InterfaceType;
            }
            set
            {
                throw new InvalidOperationException("Cannot set InterfaceType on a derived HandleExternalEventActivity.");
            }
        }

        [BrowsableAttribute(false)]
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Hidden)]
        public override string EventName
        {
            get
            {
                return base.EventName;
            }
            set
            {
                throw new InvalidOperationException("Cannot set EventName on a derived HandleExternalEventActivity.");
            }
        }

        [ValidationOptionAttribute(ValidationOption.Required)]
        public StateBehaveArgs E
        {
            get
            {
                return ((StateBehaveArgs)(this.GetValue(GoNext.EProperty)));
            }
            set
            {
                this.SetValue(GoNext.EProperty, value);
            }
        }

        protected override void OnInvoked(System.EventArgs e)
        {
            this.E = ((StateBehaveArgs)(e));
        }
    }
}
