//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("CartableEmploymentModel", "FK_wfActivityStates_wfUsers", "wfUsers", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AspHostApplication.wfUsers), "wfActivityStates", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AspHostApplication.wfActivityStates))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("CartableEmploymentModel", "FK_wfCartable_wfActivityStates", "wfActivityStates", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AspHostApplication.wfActivityStates), "wfCartable", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AspHostApplication.wfCartable))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("CartableEmploymentModel", "FK_wfCartable_wfWorkflowStatus", "wfWorkflowStatus", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AspHostApplication.wfWorkflowStatus), "wfCartable", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AspHostApplication.wfCartable))]

// Original file name:
// Generation date: 12/27/2010 11:28:18 AM
namespace AspHostApplication
{
    
    /// <summary>
    /// There are no comments for CartableEmploymentEntities in the schema.
    /// </summary>
    public partial class CartableEmploymentEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new CartableEmploymentEntities object using the connection string found in the 'CartableEmploymentEntities' section of the application configuration file.
        /// </summary>
        public CartableEmploymentEntities() : 
                base("name=CartableEmploymentEntities", "CartableEmploymentEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CartableEmploymentEntities object.
        /// </summary>
        public CartableEmploymentEntities(string connectionString) : 
                base(connectionString, "CartableEmploymentEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CartableEmploymentEntities object.
        /// </summary>
        public CartableEmploymentEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "CartableEmploymentEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for CompletedScope in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<CompletedScope> CompletedScope
        {
            get
            {
                if ((this._CompletedScope == null))
                {
                    this._CompletedScope = base.CreateQuery<CompletedScope>("[CompletedScope]");
                }
                return this._CompletedScope;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CompletedScope> _CompletedScope;
        /// <summary>
        /// There are no comments for InstanceState in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<InstanceState> InstanceState
        {
            get
            {
                if ((this._InstanceState == null))
                {
                    this._InstanceState = base.CreateQuery<InstanceState>("[InstanceState]");
                }
                return this._InstanceState;
            }
        }
        private global::System.Data.Objects.ObjectQuery<InstanceState> _InstanceState;
        /// <summary>
        /// There are no comments for sysdiagrams in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((this._sysdiagrams == null))
                {
                    this._sysdiagrams = base.CreateQuery<sysdiagrams>("[sysdiagrams]");
                }
                return this._sysdiagrams;
            }
        }
        private global::System.Data.Objects.ObjectQuery<sysdiagrams> _sysdiagrams;
        /// <summary>
        /// There are no comments for wfActivityStates in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<wfActivityStates> wfActivityStates
        {
            get
            {
                if ((this._wfActivityStates == null))
                {
                    this._wfActivityStates = base.CreateQuery<wfActivityStates>("[wfActivityStates]");
                }
                return this._wfActivityStates;
            }
        }
        private global::System.Data.Objects.ObjectQuery<wfActivityStates> _wfActivityStates;
        /// <summary>
        /// There are no comments for wfCartable in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<wfCartable> wfCartable
        {
            get
            {
                if ((this._wfCartable == null))
                {
                    this._wfCartable = base.CreateQuery<wfCartable>("[wfCartable]");
                }
                return this._wfCartable;
            }
        }
        private global::System.Data.Objects.ObjectQuery<wfCartable> _wfCartable;
        /// <summary>
        /// There are no comments for wfProfile in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<wfProfile> wfProfile
        {
            get
            {
                if ((this._wfProfile == null))
                {
                    this._wfProfile = base.CreateQuery<wfProfile>("[wfProfile]");
                }
                return this._wfProfile;
            }
        }
        private global::System.Data.Objects.ObjectQuery<wfProfile> _wfProfile;
        /// <summary>
        /// There are no comments for wfUsers in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<wfUsers> wfUsers
        {
            get
            {
                if ((this._wfUsers == null))
                {
                    this._wfUsers = base.CreateQuery<wfUsers>("[wfUsers]");
                }
                return this._wfUsers;
            }
        }
        private global::System.Data.Objects.ObjectQuery<wfUsers> _wfUsers;
        /// <summary>
        /// There are no comments for wfWorkflowStatus in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<wfWorkflowStatus> wfWorkflowStatus
        {
            get
            {
                if ((this._wfWorkflowStatus == null))
                {
                    this._wfWorkflowStatus = base.CreateQuery<wfWorkflowStatus>("[wfWorkflowStatus]");
                }
                return this._wfWorkflowStatus;
            }
        }
        private global::System.Data.Objects.ObjectQuery<wfWorkflowStatus> _wfWorkflowStatus;
        /// <summary>
        /// There are no comments for CompletedScope in the schema.
        /// </summary>
        public void AddToCompletedScope(CompletedScope completedScope)
        {
            base.AddObject("CompletedScope", completedScope);
        }
        /// <summary>
        /// There are no comments for InstanceState in the schema.
        /// </summary>
        public void AddToInstanceState(InstanceState instanceState)
        {
            base.AddObject("InstanceState", instanceState);
        }
        /// <summary>
        /// There are no comments for sysdiagrams in the schema.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
        /// <summary>
        /// There are no comments for wfActivityStates in the schema.
        /// </summary>
        public void AddTowfActivityStates(wfActivityStates wfActivityStates)
        {
            base.AddObject("wfActivityStates", wfActivityStates);
        }
        /// <summary>
        /// There are no comments for wfCartable in the schema.
        /// </summary>
        public void AddTowfCartable(wfCartable wfCartable)
        {
            base.AddObject("wfCartable", wfCartable);
        }
        /// <summary>
        /// There are no comments for wfProfile in the schema.
        /// </summary>
        public void AddTowfProfile(wfProfile wfProfile)
        {
            base.AddObject("wfProfile", wfProfile);
        }
        /// <summary>
        /// There are no comments for wfUsers in the schema.
        /// </summary>
        public void AddTowfUsers(wfUsers wfUsers)
        {
            base.AddObject("wfUsers", wfUsers);
        }
        /// <summary>
        /// There are no comments for wfWorkflowStatus in the schema.
        /// </summary>
        public void AddTowfWorkflowStatus(wfWorkflowStatus wfWorkflowStatus)
        {
            base.AddObject("wfWorkflowStatus", wfWorkflowStatus);
        }
    }
    /// <summary>
    /// There are no comments for CartableEmploymentModel.CompletedScope in the schema.
    /// </summary>
    /// <KeyProperties>
    /// uidInstanceID
    /// completedScopeID
    /// modified
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CartableEmploymentModel", Name="CompletedScope")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class CompletedScope : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CompletedScope object.
        /// </summary>
        /// <param name="uidInstanceID">Initial value of uidInstanceID.</param>
        /// <param name="completedScopeID">Initial value of completedScopeID.</param>
        /// <param name="state">Initial value of state.</param>
        /// <param name="modified">Initial value of modified.</param>
        public static CompletedScope CreateCompletedScope(global::System.Guid uidInstanceID, global::System.Guid completedScopeID, byte[] state, global::System.DateTime modified)
        {
            CompletedScope completedScope = new CompletedScope();
            completedScope.uidInstanceID = uidInstanceID;
            completedScope.completedScopeID = completedScopeID;
            completedScope.state = state;
            completedScope.modified = modified;
            return completedScope;
        }
        /// <summary>
        /// There are no comments for Property uidInstanceID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid uidInstanceID
        {
            get
            {
                return this._uidInstanceID;
            }
            set
            {
                this.OnuidInstanceIDChanging(value);
                this.ReportPropertyChanging("uidInstanceID");
                this._uidInstanceID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("uidInstanceID");
                this.OnuidInstanceIDChanged();
            }
        }
        private global::System.Guid _uidInstanceID;
        partial void OnuidInstanceIDChanging(global::System.Guid value);
        partial void OnuidInstanceIDChanged();
        /// <summary>
        /// There are no comments for Property completedScopeID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid completedScopeID
        {
            get
            {
                return this._completedScopeID;
            }
            set
            {
                this.OncompletedScopeIDChanging(value);
                this.ReportPropertyChanging("completedScopeID");
                this._completedScopeID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("completedScopeID");
                this.OncompletedScopeIDChanged();
            }
        }
        private global::System.Guid _completedScopeID;
        partial void OncompletedScopeIDChanging(global::System.Guid value);
        partial void OncompletedScopeIDChanged();
        /// <summary>
        /// There are no comments for Property state in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] state
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._state);
            }
            set
            {
                this.OnstateChanging(value);
                this.ReportPropertyChanging("state");
                this._state = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("state");
                this.OnstateChanged();
            }
        }
        private byte[] _state;
        partial void OnstateChanging(byte[] value);
        partial void OnstateChanged();
        /// <summary>
        /// There are no comments for Property modified in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime modified
        {
            get
            {
                return this._modified;
            }
            set
            {
                this.OnmodifiedChanging(value);
                this.ReportPropertyChanging("modified");
                this._modified = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("modified");
                this.OnmodifiedChanged();
            }
        }
        private global::System.DateTime _modified;
        partial void OnmodifiedChanging(global::System.DateTime value);
        partial void OnmodifiedChanged();
    }
    /// <summary>
    /// There are no comments for CartableEmploymentModel.InstanceState in the schema.
    /// </summary>
    /// <KeyProperties>
    /// uidInstanceID
    /// modified
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CartableEmploymentModel", Name="InstanceState")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class InstanceState : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new InstanceState object.
        /// </summary>
        /// <param name="uidInstanceID">Initial value of uidInstanceID.</param>
        /// <param name="modified">Initial value of modified.</param>
        public static InstanceState CreateInstanceState(global::System.Guid uidInstanceID, global::System.DateTime modified)
        {
            InstanceState instanceState = new InstanceState();
            instanceState.uidInstanceID = uidInstanceID;
            instanceState.modified = modified;
            return instanceState;
        }
        /// <summary>
        /// There are no comments for Property uidInstanceID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid uidInstanceID
        {
            get
            {
                return this._uidInstanceID;
            }
            set
            {
                this.OnuidInstanceIDChanging(value);
                this.ReportPropertyChanging("uidInstanceID");
                this._uidInstanceID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("uidInstanceID");
                this.OnuidInstanceIDChanged();
            }
        }
        private global::System.Guid _uidInstanceID;
        partial void OnuidInstanceIDChanging(global::System.Guid value);
        partial void OnuidInstanceIDChanged();
        /// <summary>
        /// There are no comments for Property state in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] state
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._state);
            }
            set
            {
                this.OnstateChanging(value);
                this.ReportPropertyChanging("state");
                this._state = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("state");
                this.OnstateChanged();
            }
        }
        private byte[] _state;
        partial void OnstateChanging(byte[] value);
        partial void OnstateChanged();
        /// <summary>
        /// There are no comments for Property status in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> status
        {
            get
            {
                return this._status;
            }
            set
            {
                this.OnstatusChanging(value);
                this.ReportPropertyChanging("status");
                this._status = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("status");
                this.OnstatusChanged();
            }
        }
        private global::System.Nullable<int> _status;
        partial void OnstatusChanging(global::System.Nullable<int> value);
        partial void OnstatusChanged();
        /// <summary>
        /// There are no comments for Property unlocked in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> unlocked
        {
            get
            {
                return this._unlocked;
            }
            set
            {
                this.OnunlockedChanging(value);
                this.ReportPropertyChanging("unlocked");
                this._unlocked = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("unlocked");
                this.OnunlockedChanged();
            }
        }
        private global::System.Nullable<int> _unlocked;
        partial void OnunlockedChanging(global::System.Nullable<int> value);
        partial void OnunlockedChanged();
        /// <summary>
        /// There are no comments for Property blocked in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> blocked
        {
            get
            {
                return this._blocked;
            }
            set
            {
                this.OnblockedChanging(value);
                this.ReportPropertyChanging("blocked");
                this._blocked = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("blocked");
                this.OnblockedChanged();
            }
        }
        private global::System.Nullable<int> _blocked;
        partial void OnblockedChanging(global::System.Nullable<int> value);
        partial void OnblockedChanged();
        /// <summary>
        /// There are no comments for Property info in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string info
        {
            get
            {
                return this._info;
            }
            set
            {
                this.OninfoChanging(value);
                this.ReportPropertyChanging("info");
                this._info = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("info");
                this.OninfoChanged();
            }
        }
        private string _info;
        partial void OninfoChanging(string value);
        partial void OninfoChanged();
        /// <summary>
        /// There are no comments for Property modified in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime modified
        {
            get
            {
                return this._modified;
            }
            set
            {
                this.OnmodifiedChanging(value);
                this.ReportPropertyChanging("modified");
                this._modified = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("modified");
                this.OnmodifiedChanged();
            }
        }
        private global::System.DateTime _modified;
        partial void OnmodifiedChanging(global::System.DateTime value);
        partial void OnmodifiedChanged();
        /// <summary>
        /// There are no comments for Property ownerID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.Guid> ownerID
        {
            get
            {
                return this._ownerID;
            }
            set
            {
                this.OnownerIDChanging(value);
                this.ReportPropertyChanging("ownerID");
                this._ownerID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ownerID");
                this.OnownerIDChanged();
            }
        }
        private global::System.Nullable<global::System.Guid> _ownerID;
        partial void OnownerIDChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnownerIDChanged();
        /// <summary>
        /// There are no comments for Property ownedUntil in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> ownedUntil
        {
            get
            {
                return this._ownedUntil;
            }
            set
            {
                this.OnownedUntilChanging(value);
                this.ReportPropertyChanging("ownedUntil");
                this._ownedUntil = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ownedUntil");
                this.OnownedUntilChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _ownedUntil;
        partial void OnownedUntilChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnownedUntilChanged();
        /// <summary>
        /// There are no comments for Property nextTimer in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> nextTimer
        {
            get
            {
                return this._nextTimer;
            }
            set
            {
                this.OnnextTimerChanging(value);
                this.ReportPropertyChanging("nextTimer");
                this._nextTimer = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("nextTimer");
                this.OnnextTimerChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _nextTimer;
        partial void OnnextTimerChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnnextTimerChanged();
    }
    /// <summary>
    /// There are no comments for CartableEmploymentModel.sysdiagrams in the schema.
    /// </summary>
    /// <KeyProperties>
    /// diagram_id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CartableEmploymentModel", Name="sysdiagrams")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class sysdiagrams : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of name.</param>
        /// <param name="principal_id">Initial value of principal_id.</param>
        /// <param name="diagram_id">Initial value of diagram_id.</param>
        public static sysdiagrams Createsysdiagrams(string name, int principal_id, int diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property principal_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int principal_id
        {
            get
            {
                return this._principal_id;
            }
            set
            {
                this.Onprincipal_idChanging(value);
                this.ReportPropertyChanging("principal_id");
                this._principal_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("principal_id");
                this.Onprincipal_idChanged();
            }
        }
        private int _principal_id;
        partial void Onprincipal_idChanging(int value);
        partial void Onprincipal_idChanged();
        /// <summary>
        /// There are no comments for Property diagram_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int diagram_id
        {
            get
            {
                return this._diagram_id;
            }
            set
            {
                this.Ondiagram_idChanging(value);
                this.ReportPropertyChanging("diagram_id");
                this._diagram_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("diagram_id");
                this.Ondiagram_idChanged();
            }
        }
        private int _diagram_id;
        partial void Ondiagram_idChanging(int value);
        partial void Ondiagram_idChanged();
        /// <summary>
        /// There are no comments for Property version in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> version
        {
            get
            {
                return this._version;
            }
            set
            {
                this.OnversionChanging(value);
                this.ReportPropertyChanging("version");
                this._version = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("version");
                this.OnversionChanged();
            }
        }
        private global::System.Nullable<int> _version;
        partial void OnversionChanging(global::System.Nullable<int> value);
        partial void OnversionChanged();
        /// <summary>
        /// There are no comments for Property definition in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] definition
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._definition);
            }
            set
            {
                this.OndefinitionChanging(value);
                this.ReportPropertyChanging("definition");
                this._definition = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("definition");
                this.OndefinitionChanged();
            }
        }
        private byte[] _definition;
        partial void OndefinitionChanging(byte[] value);
        partial void OndefinitionChanged();
    }
    /// <summary>
    /// There are no comments for CartableEmploymentModel.wfActivityStates in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ActivityStateName
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CartableEmploymentModel", Name="wfActivityStates")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class wfActivityStates : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new wfActivityStates object.
        /// </summary>
        /// <param name="activityStateName">Initial value of ActivityStateName.</param>
        /// <param name="oBJ_VERSION">Initial value of OBJ_VERSION.</param>
        /// <param name="title">Initial value of Title.</param>
        /// <param name="pageKey">Initial value of PageKey.</param>
        public static wfActivityStates CreatewfActivityStates(string activityStateName, decimal oBJ_VERSION, string title, string pageKey)
        {
            wfActivityStates wfActivityStates = new wfActivityStates();
            wfActivityStates.ActivityStateName = activityStateName;
            wfActivityStates.OBJ_VERSION = oBJ_VERSION;
            wfActivityStates.Title = title;
            wfActivityStates.PageKey = pageKey;
            return wfActivityStates;
        }
        /// <summary>
        /// There are no comments for Property ActivityStateName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ActivityStateName
        {
            get
            {
                return this._ActivityStateName;
            }
            set
            {
                this.OnActivityStateNameChanging(value);
                this.ReportPropertyChanging("ActivityStateName");
                this._ActivityStateName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ActivityStateName");
                this.OnActivityStateNameChanged();
            }
        }
        private string _ActivityStateName;
        partial void OnActivityStateNameChanging(string value);
        partial void OnActivityStateNameChanged();
        /// <summary>
        /// There are no comments for Property OBJ_VERSION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OBJ_VERSION
        {
            get
            {
                return this._OBJ_VERSION;
            }
            set
            {
                this.OnOBJ_VERSIONChanging(value);
                this.ReportPropertyChanging("OBJ_VERSION");
                this._OBJ_VERSION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("OBJ_VERSION");
                this.OnOBJ_VERSIONChanged();
            }
        }
        private decimal _OBJ_VERSION;
        partial void OnOBJ_VERSIONChanging(decimal value);
        partial void OnOBJ_VERSIONChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property PageKey in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PageKey
        {
            get
            {
                return this._PageKey;
            }
            set
            {
                this.OnPageKeyChanging(value);
                this.ReportPropertyChanging("PageKey");
                this._PageKey = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PageKey");
                this.OnPageKeyChanged();
            }
        }
        private string _PageKey;
        partial void OnPageKeyChanging(string value);
        partial void OnPageKeyChanged();
        /// <summary>
        /// There are no comments for wfUsers in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CartableEmploymentModel", "FK_wfActivityStates_wfUsers", "wfUsers")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public wfUsers wfUsers
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<wfUsers>("CartableEmploymentModel.FK_wfActivityStates_wfUsers", "wfUsers").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<wfUsers>("CartableEmploymentModel.FK_wfActivityStates_wfUsers", "wfUsers").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for wfUsers in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<wfUsers> wfUsersReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<wfUsers>("CartableEmploymentModel.FK_wfActivityStates_wfUsers", "wfUsers");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<wfUsers>("CartableEmploymentModel.FK_wfActivityStates_wfUsers", "wfUsers", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for wfCartable in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CartableEmploymentModel", "FK_wfCartable_wfActivityStates", "wfCartable")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<wfCartable> wfCartable
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<wfCartable>("CartableEmploymentModel.FK_wfCartable_wfActivityStates", "wfCartable");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<wfCartable>("CartableEmploymentModel.FK_wfCartable_wfActivityStates", "wfCartable", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for CartableEmploymentModel.wfCartable in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CartableId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CartableEmploymentModel", Name="wfCartable")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class wfCartable : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new wfCartable object.
        /// </summary>
        /// <param name="cartableId">Initial value of CartableId.</param>
        /// <param name="workflowId">Initial value of WorkflowId.</param>
        public static wfCartable CreatewfCartable(global::System.Guid cartableId, global::System.Guid workflowId)
        {
            wfCartable wfCartable = new wfCartable();
            wfCartable.CartableId = cartableId;
            wfCartable.WorkflowId = workflowId;
            return wfCartable;
        }
        /// <summary>
        /// There are no comments for Property CartableId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid CartableId
        {
            get
            {
                return this._CartableId;
            }
            set
            {
                this.OnCartableIdChanging(value);
                this.ReportPropertyChanging("CartableId");
                this._CartableId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CartableId");
                this.OnCartableIdChanged();
            }
        }
        private global::System.Guid _CartableId;
        partial void OnCartableIdChanging(global::System.Guid value);
        partial void OnCartableIdChanged();
        /// <summary>
        /// There are no comments for Property WorkflowId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid WorkflowId
        {
            get
            {
                return this._WorkflowId;
            }
            set
            {
                this.OnWorkflowIdChanging(value);
                this.ReportPropertyChanging("WorkflowId");
                this._WorkflowId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("WorkflowId");
                this.OnWorkflowIdChanged();
            }
        }
        private global::System.Guid _WorkflowId;
        partial void OnWorkflowIdChanging(global::System.Guid value);
        partial void OnWorkflowIdChanged();
        /// <summary>
        /// There are no comments for Property ParentWorkflowId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.Guid> ParentWorkflowId
        {
            get
            {
                return this._ParentWorkflowId;
            }
            set
            {
                this.OnParentWorkflowIdChanging(value);
                this.ReportPropertyChanging("ParentWorkflowId");
                this._ParentWorkflowId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ParentWorkflowId");
                this.OnParentWorkflowIdChanged();
            }
        }
        private global::System.Nullable<global::System.Guid> _ParentWorkflowId;
        partial void OnParentWorkflowIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnParentWorkflowIdChanged();
        /// <summary>
        /// There are no comments for Property ItemId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ItemId
        {
            get
            {
                return this._ItemId;
            }
            set
            {
                this.OnItemIdChanging(value);
                this.ReportPropertyChanging("ItemId");
                this._ItemId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ItemId");
                this.OnItemIdChanged();
            }
        }
        private global::System.Nullable<int> _ItemId;
        partial void OnItemIdChanging(global::System.Nullable<int> value);
        partial void OnItemIdChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property CreateDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return this._CreateDate;
            }
            set
            {
                this.OnCreateDateChanging(value);
                this.ReportPropertyChanging("CreateDate");
                this._CreateDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreateDate");
                this.OnCreateDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
        /// <summary>
        /// There are no comments for Property ActionDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> ActionDate
        {
            get
            {
                return this._ActionDate;
            }
            set
            {
                this.OnActionDateChanging(value);
                this.ReportPropertyChanging("ActionDate");
                this._ActionDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ActionDate");
                this.OnActionDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _ActionDate;
        partial void OnActionDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnActionDateChanged();
        /// <summary>
        /// There are no comments for wfActivityStates in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CartableEmploymentModel", "FK_wfCartable_wfActivityStates", "wfActivityStates")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public wfActivityStates wfActivityStates
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<wfActivityStates>("CartableEmploymentModel.FK_wfCartable_wfActivityStates", "wfActivityStates").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<wfActivityStates>("CartableEmploymentModel.FK_wfCartable_wfActivityStates", "wfActivityStates").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for wfActivityStates in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<wfActivityStates> wfActivityStatesReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<wfActivityStates>("CartableEmploymentModel.FK_wfCartable_wfActivityStates", "wfActivityStates");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<wfActivityStates>("CartableEmploymentModel.FK_wfCartable_wfActivityStates", "wfActivityStates", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for wfWorkflowStatus in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CartableEmploymentModel", "FK_wfCartable_wfWorkflowStatus", "wfWorkflowStatus")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public wfWorkflowStatus wfWorkflowStatus
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<wfWorkflowStatus>("CartableEmploymentModel.FK_wfCartable_wfWorkflowStatus", "wfWorkflowStatus").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<wfWorkflowStatus>("CartableEmploymentModel.FK_wfCartable_wfWorkflowStatus", "wfWorkflowStatus").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for wfWorkflowStatus in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<wfWorkflowStatus> wfWorkflowStatusReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<wfWorkflowStatus>("CartableEmploymentModel.FK_wfCartable_wfWorkflowStatus", "wfWorkflowStatus");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<wfWorkflowStatus>("CartableEmploymentModel.FK_wfCartable_wfWorkflowStatus", "wfWorkflowStatus", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for CartableEmploymentModel.wfProfile in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CartableEmploymentModel", Name="wfProfile")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class wfProfile : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new wfProfile object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        public static wfProfile CreatewfProfile(int id)
        {
            wfProfile wfProfile = new wfProfile();
            wfProfile.Id = id;
            return wfProfile;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Age in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Age
        {
            get
            {
                return this._Age;
            }
            set
            {
                this.OnAgeChanging(value);
                this.ReportPropertyChanging("Age");
                this._Age = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Age");
                this.OnAgeChanged();
            }
        }
        private global::System.Nullable<int> _Age;
        partial void OnAgeChanging(global::System.Nullable<int> value);
        partial void OnAgeChanged();
        /// <summary>
        /// There are no comments for Property FistName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FistName
        {
            get
            {
                return this._FistName;
            }
            set
            {
                this.OnFistNameChanging(value);
                this.ReportPropertyChanging("FistName");
                this._FistName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("FistName");
                this.OnFistNameChanged();
            }
        }
        private string _FistName;
        partial void OnFistNameChanging(string value);
        partial void OnFistNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this.ReportPropertyChanging("LastName");
                this._LastName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("LastName");
                this.OnLastNameChanged();
            }
        }
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property IdentityNo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> IdentityNo
        {
            get
            {
                return this._IdentityNo;
            }
            set
            {
                this.OnIdentityNoChanging(value);
                this.ReportPropertyChanging("IdentityNo");
                this._IdentityNo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdentityNo");
                this.OnIdentityNoChanged();
            }
        }
        private global::System.Nullable<int> _IdentityNo;
        partial void OnIdentityNoChanging(global::System.Nullable<int> value);
        partial void OnIdentityNoChanged();
        /// <summary>
        /// There are no comments for Property Gender in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this._Gender;
            }
            set
            {
                this.OnGenderChanging(value);
                this.ReportPropertyChanging("Gender");
                this._Gender = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Gender");
                this.OnGenderChanged();
            }
        }
        private string _Gender;
        partial void OnGenderChanging(string value);
        partial void OnGenderChanged();
        /// <summary>
        /// There are no comments for Property Degree in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Degree
        {
            get
            {
                return this._Degree;
            }
            set
            {
                this.OnDegreeChanging(value);
                this.ReportPropertyChanging("Degree");
                this._Degree = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Degree");
                this.OnDegreeChanged();
            }
        }
        private string _Degree;
        partial void OnDegreeChanging(string value);
        partial void OnDegreeChanged();
        /// <summary>
        /// There are no comments for Property RegistDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> RegistDate
        {
            get
            {
                return this._RegistDate;
            }
            set
            {
                this.OnRegistDateChanging(value);
                this.ReportPropertyChanging("RegistDate");
                this._RegistDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("RegistDate");
                this.OnRegistDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _RegistDate;
        partial void OnRegistDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnRegistDateChanged();
        /// <summary>
        /// There are no comments for Property IsRegisterOk in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> IsRegisterOk
        {
            get
            {
                return this._IsRegisterOk;
            }
            set
            {
                this.OnIsRegisterOkChanging(value);
                this.ReportPropertyChanging("IsRegisterOk");
                this._IsRegisterOk = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsRegisterOk");
                this.OnIsRegisterOkChanged();
            }
        }
        private global::System.Nullable<bool> _IsRegisterOk;
        partial void OnIsRegisterOkChanging(global::System.Nullable<bool> value);
        partial void OnIsRegisterOkChanged();
        /// <summary>
        /// There are no comments for Property Occupation in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Occupation
        {
            get
            {
                return this._Occupation;
            }
            set
            {
                this.OnOccupationChanging(value);
                this.ReportPropertyChanging("Occupation");
                this._Occupation = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Occupation");
                this.OnOccupationChanged();
            }
        }
        private string _Occupation;
        partial void OnOccupationChanging(string value);
        partial void OnOccupationChanged();
        /// <summary>
        /// There are no comments for Property YearExperiences in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string YearExperiences
        {
            get
            {
                return this._YearExperiences;
            }
            set
            {
                this.OnYearExperiencesChanging(value);
                this.ReportPropertyChanging("YearExperiences");
                this._YearExperiences = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("YearExperiences");
                this.OnYearExperiencesChanged();
            }
        }
        private string _YearExperiences;
        partial void OnYearExperiencesChanging(string value);
        partial void OnYearExperiencesChanged();
        /// <summary>
        /// There are no comments for Property Experiences in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Experiences
        {
            get
            {
                return this._Experiences;
            }
            set
            {
                this.OnExperiencesChanging(value);
                this.ReportPropertyChanging("Experiences");
                this._Experiences = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Experiences");
                this.OnExperiencesChanged();
            }
        }
        private string _Experiences;
        partial void OnExperiencesChanging(string value);
        partial void OnExperiencesChanged();
        /// <summary>
        /// There are no comments for Property Interesting in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Interesting
        {
            get
            {
                return this._Interesting;
            }
            set
            {
                this.OnInterestingChanging(value);
                this.ReportPropertyChanging("Interesting");
                this._Interesting = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Interesting");
                this.OnInterestingChanged();
            }
        }
        private string _Interesting;
        partial void OnInterestingChanging(string value);
        partial void OnInterestingChanged();
        /// <summary>
        /// There are no comments for Property IsDocumentsOK in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> IsDocumentsOK
        {
            get
            {
                return this._IsDocumentsOK;
            }
            set
            {
                this.OnIsDocumentsOKChanging(value);
                this.ReportPropertyChanging("IsDocumentsOK");
                this._IsDocumentsOK = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsDocumentsOK");
                this.OnIsDocumentsOKChanged();
            }
        }
        private global::System.Nullable<bool> _IsDocumentsOK;
        partial void OnIsDocumentsOKChanging(global::System.Nullable<bool> value);
        partial void OnIsDocumentsOKChanged();
        /// <summary>
        /// There are no comments for Property IQScore in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> IQScore
        {
            get
            {
                return this._IQScore;
            }
            set
            {
                this.OnIQScoreChanging(value);
                this.ReportPropertyChanging("IQScore");
                this._IQScore = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IQScore");
                this.OnIQScoreChanged();
            }
        }
        private global::System.Nullable<int> _IQScore;
        partial void OnIQScoreChanging(global::System.Nullable<int> value);
        partial void OnIQScoreChanged();
        /// <summary>
        /// There are no comments for Property LanguageScore in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> LanguageScore
        {
            get
            {
                return this._LanguageScore;
            }
            set
            {
                this.OnLanguageScoreChanging(value);
                this.ReportPropertyChanging("LanguageScore");
                this._LanguageScore = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LanguageScore");
                this.OnLanguageScoreChanged();
            }
        }
        private global::System.Nullable<int> _LanguageScore;
        partial void OnLanguageScoreChanging(global::System.Nullable<int> value);
        partial void OnLanguageScoreChanged();
        /// <summary>
        /// There are no comments for Property TechnicalScore in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> TechnicalScore
        {
            get
            {
                return this._TechnicalScore;
            }
            set
            {
                this.OnTechnicalScoreChanging(value);
                this.ReportPropertyChanging("TechnicalScore");
                this._TechnicalScore = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TechnicalScore");
                this.OnTechnicalScoreChanged();
            }
        }
        private global::System.Nullable<int> _TechnicalScore;
        partial void OnTechnicalScoreChanging(global::System.Nullable<int> value);
        partial void OnTechnicalScoreChanged();
        /// <summary>
        /// There are no comments for Property PersonalityScore in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> PersonalityScore
        {
            get
            {
                return this._PersonalityScore;
            }
            set
            {
                this.OnPersonalityScoreChanging(value);
                this.ReportPropertyChanging("PersonalityScore");
                this._PersonalityScore = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PersonalityScore");
                this.OnPersonalityScoreChanged();
            }
        }
        private global::System.Nullable<int> _PersonalityScore;
        partial void OnPersonalityScoreChanging(global::System.Nullable<int> value);
        partial void OnPersonalityScoreChanged();
    }
    /// <summary>
    /// There are no comments for CartableEmploymentModel.wfUsers in the schema.
    /// </summary>
    /// <KeyProperties>
    /// UserName
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CartableEmploymentModel", Name="wfUsers")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class wfUsers : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new wfUsers object.
        /// </summary>
        /// <param name="userName">Initial value of UserName.</param>
        public static wfUsers CreatewfUsers(string userName)
        {
            wfUsers wfUsers = new wfUsers();
            wfUsers.UserName = userName;
            return wfUsers;
        }
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this.ReportPropertyChanging("UserName");
                this._UserName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("UserName");
                this.OnUserNameChanged();
            }
        }
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this.ReportPropertyChanging("Password");
                this._Password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Password");
                this.OnPasswordChanged();
            }
        }
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for wfActivityStates in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CartableEmploymentModel", "FK_wfActivityStates_wfUsers", "wfActivityStates")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<wfActivityStates> wfActivityStates
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<wfActivityStates>("CartableEmploymentModel.FK_wfActivityStates_wfUsers", "wfActivityStates");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<wfActivityStates>("CartableEmploymentModel.FK_wfActivityStates_wfUsers", "wfActivityStates", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for CartableEmploymentModel.wfWorkflowStatus in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Status
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CartableEmploymentModel", Name="wfWorkflowStatus")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class wfWorkflowStatus : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new wfWorkflowStatus object.
        /// </summary>
        /// <param name="status">Initial value of Status.</param>
        public static wfWorkflowStatus CreatewfWorkflowStatus(string status)
        {
            wfWorkflowStatus wfWorkflowStatus = new wfWorkflowStatus();
            wfWorkflowStatus.Status = status;
            return wfWorkflowStatus;
        }
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this.ReportPropertyChanging("Status");
                this._Status = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Status");
                this.OnStatusChanged();
            }
        }
        private string _Status;
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property StatusName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusName
        {
            get
            {
                return this._StatusName;
            }
            set
            {
                this.OnStatusNameChanging(value);
                this.ReportPropertyChanging("StatusName");
                this._StatusName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("StatusName");
                this.OnStatusNameChanged();
            }
        }
        private string _StatusName;
        partial void OnStatusNameChanging(string value);
        partial void OnStatusNameChanged();
        /// <summary>
        /// There are no comments for wfCartable in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CartableEmploymentModel", "FK_wfCartable_wfWorkflowStatus", "wfCartable")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<wfCartable> wfCartable
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<wfCartable>("CartableEmploymentModel.FK_wfCartable_wfWorkflowStatus", "wfCartable");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<wfCartable>("CartableEmploymentModel.FK_wfCartable_wfWorkflowStatus", "wfCartable", value);
                }
            }
        }
    }
}
